"""Refine balancing: bring every label up to a minimum number of rows.

Real WLO data is unevenly distributed — a few hundred rows for one subject, three
for another — and a label the model has seen three times is a label it cannot
learn. This module generates the missing rows for each short label FROM THAT
LABEL'S OWN REAL EXAMPLES, so the new text resembles the material the label
actually describes rather than a generic paragraph about the subject.

``plan_balance`` is the preview and stays pure: it answers what would be generated
and how many model calls it could take, before anything is paid for. The model
calls and the gates on their answers live in ``balance_gates.py``, the prompt in
``balance_prompt.py``.
"""

from __future__ import annotations

import asyncio
import math
from collections import defaultdict
from collections.abc import Callable
from dataclasses import dataclass

import pandas as pd

from ..textnorm import split_labels
from .balance_gates import (
    EXTRA_BATCHES,
    Complete,
    LabelResult,
    fingerprint,
    generate_for_label,
    pick_examples,
)
from .balance_prompt import PromptContext, entries_per_call
from .fields import TextField, read_values, write_values
from .prompt_context import FieldShape, contrast_labels, display_names, field_shapes
from .provenance import (
    ENRICHED_FIELDS,
    EXAMPLE_FOR,
    GENERATED_FOR,
    MARK_COLUMNS,
    enriched_columns,
    is_marked,
)


@dataclass(frozen=True)
class _Prepared:
    """Everything balancing reads from the frame, read once and column by column.

    Per-row ``df.iloc`` access took seconds on a 30k-row frame — on the event loop.
    Reading each column once is the same information for a fraction of the time.
    """

    cells: list[list[str]]               # per row: each field's cell, normalised
    real: list[bool]                     # per row: not generated by an earlier run
    rows_by_label: dict[str, list[int]]  # label -> row positions
    foreign_marks: dict                  # marks that are not labels here, named
    labels_of_row: list[list[str]]       # per row: its labels, each once
    names: dict[str, str]                # label -> the name people read (<column>_DISPLAYNAME)
    completed: list[list[bool]]          # per row and field: a cell enrichment wrote

    def usable(self, position: int) -> bool:
        """A real row with some text: the only kind worth showing the generator."""
        return self.real[position] and any(self.cells[position])

    def untouched(self, position: int) -> list[str]:
        """The row's cells with the ones enrichment wrote blanked: what people wrote,
        the only thing the dataset's lengths may be measured on."""
        return ["" if llm else cell
                for cell, llm in zip(self.cells[position], self.completed[position], strict=True)]


def _prepare(
    df: pd.DataFrame, fields: list[TextField], label_column: str, label_separator: str
) -> _Prepared:
    if not fields:
        raise ValueError("Balancing needs at least one text field.")
    columns = [
        [write_values(read_values(cell, f), f) for cell in df[f.column]]
        if f.column in df.columns else [""] * len(df)
        for f in fields
    ]
    marks = df[GENERATED_FOR] if GENERATED_FOR in df.columns else None
    filled = ([enriched_columns(cell) for cell in df[ENRICHED_FIELDS]]
              if ENRICHED_FIELDS in df.columns else [frozenset()] * len(df))
    rows: dict[str, list[int]] = defaultdict(list)
    labels_of_row: list[list[str]] = []
    for position, cell in enumerate(df[label_column]):
        labels = list(dict.fromkeys(split_labels(cell, label_separator)))
        labels_of_row.append(labels)
        for label in labels:
            rows[label].append(position)
    # Marks that are not labels of this column: from a balance on another label
    # column, or a column of the user's that shares the name. Combine and re-import
    # lose the history that could tell the two apart, so they are NAMED, not refused
    # — and treated as generated either way, which never lets them into a holdout.
    foreign = [] if marks is None else [
        str(c).strip() for c in marks if is_marked(c) and str(c).strip() not in rows]
    return _Prepared(
        cells=[list(row) for row in zip(*columns, strict=True)],
        real=[True] * len(df) if marks is None else [not is_marked(c) for c in marks],
        rows_by_label=dict(rows),
        foreign_marks={"rows": len(foreign), "example": min(foreign) if foreign else None,
                       "column": label_column},
        labels_of_row=labels_of_row,
        names=display_names(df, label_column, label_separator),
        completed=[[f.column in columns for f in fields] for columns in filled],
    )


def _plan(prepared: _Prepared, target: int, batch_size: int, limit: int | None,
          per_call: Callable[[str], int] | None = None) -> dict:
    """``per_call`` says how many entries one call for a label asks for -- fewer than
    ``batch_size`` where the answer would not fit the output cap -- so the batches, and
    the call budget checked against them, are the ones the run makes."""
    per_label: dict[str, dict] = {}
    skipped: list[str] = []
    remaining = math.inf if limit is None else limit
    # Shortest labels first: when `limit` cuts the run, the neediest got their rows.
    for label, rows in sorted(prepared.rows_by_label.items(), key=lambda kv: len(kv[1])):
        support = len(rows)
        deficit = max(0, target - support)
        if deficit and not any(prepared.usable(p) for p in rows):
            # Nothing real to imitate. Inventing rows from the bare label name — or
            # from earlier generated rows — is the generic filler this exists to avoid.
            skipped.append(label)
            continue
        planned = int(min(deficit, remaining))
        remaining -= planned
        synthetic = sum(1 for p in rows if not prepared.real[p])
        per_label[label] = {
            "support": support,
            "deficit": deficit,
            "planned": planned,
            "batches": math.ceil(planned / (per_call(label) if per_call and planned
                                             else batch_size)),
            "synthetic_share": round((synthetic + planned) / (support + planned), 3),
        }
    entries = per_label.values()
    return {
        "target_per_label": target,
        "rows_to_add": sum(e["planned"] for e in entries),
        "batches": sum(e["batches"] for e in entries),
        # The worst case: every label that is generated for may use its retries.
        "max_batches": sum(e["batches"] + EXTRA_BATCHES for e in entries if e["planned"]),
        "labels_below_target": sum(1 for e in entries if e["deficit"]),
        "labels_cut_by_limit": sorted(k for k, e in per_label.items() if e["planned"] < e["deficit"]),
        "skipped_without_examples": sorted(skipped),
        "foreign_marks": prepared.foreign_marks,
        "per_label": per_label,
    }


def plan_balance(
    df: pd.DataFrame,
    *,
    fields: list[TextField],
    label_column: str,
    target_per_label: int,
    label_separator: str = ",",
    batch_size: int = 10,
    limit: int | None = None,
    examples_per_label: int = 4,
) -> dict:
    """What balancing to ``target_per_label`` would generate, and what it could cost.

    Per label: the support, the ``deficit`` the label has, the rows this run would
    generate (``planned`` — less than the deficit when ``limit`` cuts the run), the
    batches, and the share of the label's rows that would then be synthetic, earlier
    generated rows included. A label lifted from 3 to 100 is 97 % invented, and that
    belongs in front of the user before the run, not in a footnote after it.
    """
    prepared, _, dataset_shapes = _read_frame(df, fields, label_column, label_separator)
    return _plan(prepared, target_per_label, batch_size, limit,
                 _fitting(prepared, fields, dataset_shapes, batch_size, examples_per_label))


def _add_mark(existing: object, label: str, separator: str) -> str:
    """``label`` added to a row's example mark, a list in the LABEL separator: labels
    were split with it, so none of them can contain it — split on "," instead,
    "Politik, Gesellschaft" was not recognised and written again by every run."""
    marks = split_labels(existing, separator) if is_marked(existing) else []
    return separator.join(marks if label in marks else [*marks, label])


def _assemble(
    df: pd.DataFrame, generated: list[dict], examples: list[tuple[int, str]], separator: str
) -> pd.DataFrame:
    new = df.copy()
    for column in MARK_COLUMNS:
        new[column] = [c if is_marked(c) else "" for c in new[column]] if column in new else ""
    position_of = new.columns.get_loc(EXAMPLE_FOR)
    for position, label in examples:
        new.iat[position, position_of] = _add_mark(new.iat[position, position_of], label, separator)
    if not generated:
        return new
    # Every column filled on the NEW rows before the concat: a column missing there
    # would come back as NaN and turn a real row's integer id into a float.
    added = pd.DataFrame(generated, columns=new.columns).fillna("")
    return pd.concat([new, added], ignore_index=True)


def _read_frame(
    df: pd.DataFrame, fields: list[TextField], label_column: str, label_separator: str,
) -> tuple[_Prepared, set[str], list[FieldShape | None]]:
    """The synchronous part before the first model call — run off the event loop. The
    shapes are the whole dataset's: a label with too few filled cells borrows them."""
    prepared = _prepare(df, fields, label_column, label_separator)
    real = [prepared.untouched(p) for p in range(len(prepared.cells)) if prepared.usable(p)]
    return prepared, {fingerprint(row) for row in prepared.cells}, field_shapes(real, fields)


def _context(prepared: _Prepared, label: str,
             shapes: tuple[FieldShape | None, ...]) -> PromptContext:
    """What the prompt for ``label`` is told about the dataset (``prompt_context``)."""
    others, more = contrast_labels(label, prepared.rows_by_label, prepared.labels_of_row,
                                   prepared.names)
    return PromptContext(label_name=prepared.names.get(label), others=tuple(others),
                         more_others=more, shapes=shapes)


def _label_inputs(prepared: _Prepared, label: str, fields: list[TextField],
                  dataset_shapes: list[FieldShape | None], examples_per_label: int,
                  ) -> tuple[list[int], list[dict], tuple[FieldShape | None, ...]]:
    """The example rows (positions, and as ``{column: cell}``) and the field shapes
    generation for ``label`` works from -- the same for the preview and the run."""
    usable = [p for p in prepared.rows_by_label[label] if prepared.usable(p)]
    positions = pick_examples(usable, prepared.cells, examples_per_label,
                              touched={p for p in usable if any(prepared.completed[p])})
    examples = [dict(zip((f.column for f in fields), prepared.cells[p], strict=True))
                for p in positions]
    shapes = field_shapes([prepared.untouched(p) for p in usable], fields,
                          fallback=dataset_shapes)
    return positions, examples, tuple(shapes)


def _fitting(prepared: _Prepared, fields: list[TextField],
             dataset_shapes: list[FieldShape | None], batch_size: int,
             examples_per_label: int) -> Callable[[str], int]:
    """Per label, the entries one call asks for (``entries_per_call``): its answer is
    sized by the examples and the field shapes, never by the contrast list."""
    def per_call(label: str) -> int:
        _, examples, shapes = _label_inputs(prepared, label, fields, dataset_shapes,
                                            examples_per_label)
        return entries_per_call(examples, fields, batch_size, PromptContext(shapes=shapes))
    return per_call


async def balance_dataset(
    df: pd.DataFrame,
    *,
    fields: list[TextField],
    label_column: str,
    target_per_label: int,
    complete: Complete,
    label_separator: str = ",",
    examples_per_label: int = 4,
    batch_size: int = 10,
    limit: int = 500,
    stop_on: tuple[type[BaseException], ...] = (),
) -> tuple[pd.DataFrame, dict]:
    """Generate the rows each short label is missing; returns the new frame and stats.

    The source frame is never modified — the caller saves the result as a NEW dataset.
    Real rows shown to the generator are marked ``example_for``, generated rows
    ``generated_for``; the split keeps both out of a holdout.

    An exception in ``stop_on`` — a budget cap, typically — ends the run early
    instead of failing it: the rows generated so far were paid for and are kept, and
    ``stopped`` says why the run ended. Anything else propagates.

    ``generated_for`` values that are not labels in ``label_column`` are named in
    ``foreign_marks`` and treated as generated; they do not stop the run.
    """
    prepared, seen, dataset_shapes = await asyncio.to_thread(
        _read_frame, df, fields, label_column, label_separator)
    plan = await asyncio.to_thread(
        _plan, prepared, target_per_label, batch_size, limit,
        _fitting(prepared, fields, dataset_shapes, batch_size, examples_per_label))
    generated: list[dict] = []
    shown: list[tuple[int, str]] = []
    per_label: dict[str, dict] = {}
    stopped: str | None = None

    for label, entry in plan["per_label"].items():
        if not entry["deficit"]:
            continue
        rows = prepared.rows_by_label[label]
        synthetic = sum(1 for p in rows if not prepared.real[p])
        result = LabelResult()
        if entry["planned"] and stopped is None:
            positions, examples, shapes = _label_inputs(prepared, label, fields, dataset_shapes,
                                                        examples_per_label)
            result = await generate_for_label(
                label, examples, fields=fields, wanted=entry["planned"],
                avoid=[prepared.cells[p][0] for p in rows], seen=seen,
                batch_size=batch_size, complete=complete, stop_on=stop_on,
                context=_context(prepared, label, shapes),
            )
            if result.sent:  # a call that never went out showed nobody anything
                shown.extend((p, label) for p in positions)
            generated.extend(
                {**dict(zip((f.column for f in fields), cells, strict=True)),
                 label_column: label, GENERATED_FOR: label}
                for cells in result.accepted
            )
            stopped = result.stopped
        added = len(result.accepted)
        per_label[label] = {
            "support": entry["support"],
            "added": added,
            "missing": entry["deficit"] - added,
            "synthetic_share": round((synthetic + added) / (entry["support"] + added), 3),
            **result.counters,
        }

    new = await asyncio.to_thread(_assemble, df, generated, shown, label_separator)
    return new, {
        "target_per_label": target_per_label,
        "rows_added": len(generated),
        "labels_filled": sum(1 for e in per_label.values() if not e["missing"]),
        "labels_cut_by_limit": plan["labels_cut_by_limit"],
        "skipped_without_examples": plan["skipped_without_examples"],
        "stopped": stopped,
        "foreign_marks": plan["foreign_marks"],
        "per_label": per_label,
    }
